// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "d687f97a-a31e-483a-85ab-8332753df584");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1576056580);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1576056610);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1);
user_pref("browser.cache.disk.capacity", 532480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1576056549);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c8395a56-3d06-47f7-9861-c84fbc78c8d0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.slowStartup.averageTime", 1517);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191205184924");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1576056550);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"826d92ae-4e0f-4101-a840-558fddb2f003\",\"screenshots@mozilla.org\":\"446d900e-ea60-45e9-b17d-6e9eb06b4405\",\"webcompat-reporter@mozilla.org\":\"cb8b0940-e667-44c2-884f-e35fd7383a25\",\"webcompat@mozilla.org\":\"065e7d02-a38d-4b95-a178-a97764a5dc73\",\"default-theme@mozilla.org\":\"56a6d4c5-bb72-4f0e-9018-637dd5504f00\",\"google@search.mozilla.org\":\"08d6f7ed-0912-41b4-867b-f897fd4ae2cb\",\"amazondotcom@search.mozilla.org\":\"005a5834-b979-40ad-9ab6-97004ebc9da3\",\"bing@search.mozilla.org\":\"1447c8f3-9f5a-4100-b658-a7e20b3411f5\",\"ddg@search.mozilla.org\":\"e07d5235-350f-4a4f-b7c9-c14644238204\",\"ebay@search.mozilla.org\":\"8034bf69-a3da-4113-9110-946651d0fa35\",\"twitter@search.mozilla.org\":\"5160a7c3-cf78-4c4d-a5c1-b15abb61c0c1\",\"wikipedia@search.mozilla.org\":\"d2926911-5d1f-4f5e-b916-4aaf988a908c\"}");
user_pref("media.gmp-manager.buildID", "20191205184924");
user_pref("media.gmp-manager.lastCheck", 1576056626);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8cca15e0-d483-4f96-9df8-58818d6ba674");
user_pref("security.sandbox.plugin.tempDirSuffix", "937d07bf-c012-4093-b352-1e5f5cbee101");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1576056548);
user_pref("toolkit.telemetry.cachedClientID", "2ae40fb3-4177-4dee-87c1-8f1ee4c57af1");
user_pref("toolkit.telemetry.previousBuildID", "20191205184924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "modal_variant_b");
