// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567762911);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567763031);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567766031);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567762671);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567762551);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1567762791);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567763271);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567763151);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 829440);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567762401);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6078a382-09bb-469b-9c81-b9f04f004f9a}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567717200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568968523");
user_pref("browser.slowStartup.averageTime", 2162);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1568968523);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567762583588");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1567763092);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"09bc420a-bdce-4bca-875f-9127166386be\",\"screenshots@mozilla.org\":\"cf98a19a-b93c-499f-8586-8f9f92ec41c6\",\"webcompat-reporter@mozilla.org\":\"5d7eea1a-e154-4ee6-9c02-15d8d1bf053a\",\"webcompat@mozilla.org\":\"ae34a22b-fdd9-49d1-ae6f-bf42fdadf8ea\",\"fxmonitor@mozilla.org\":\"b0f0bf0b-f817-4602-93bc-012c60cf006b\",\"default-theme@mozilla.org\":\"d9b267bb-b997-4573-80cd-6e993f08f752\",\"google@search.mozilla.org\":\"752bbeab-5851-45bb-9891-818063bc681d\",\"amazondotcom@search.mozilla.org\":\"38d48e11-ab39-470b-9248-8cf703de1002\",\"bing@search.mozilla.org\":\"f487071c-6f25-478b-a5b8-ee746ff29217\",\"ddg@search.mozilla.org\":\"1e77906c-c41b-4f25-98bf-7a3002abd550\",\"ebay@search.mozilla.org\":\"2842fac4-00be-4c29-bf3c-19cd208596dd\",\"twitter@search.mozilla.org\":\"889a0dca-9cb4-465c-8357-5cebd7c33f08\",\"wikipedia@search.mozilla.org\":\"b8c5eabc-382e-483c-8644-a8f87aa51a98\"}");
user_pref("idle.lastDailyNotification", 1567762869);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190327091052");
user_pref("media.gmp-manager.lastCheck", 1567762569);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567762869);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "9a6a7d01-5795-44ac-8ae9-fd401d8fdd38");
user_pref("security.sandbox.plugin.tempDirSuffix", "8b102cce-37b0-475c-8815-6d8468610d1e");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1567762869);
user_pref("toolkit.startup.last_success", 1568968520);
user_pref("toolkit.telemetry.cachedClientID", "0c21c679-f719-4a8b-923d-a21c5c54d315");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
