// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567762377);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567762617);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567762497);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1568367407);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 44);
user_pref("browser.cache.disk.capacity", 829440);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567762346);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a925540e-cf68-4881-89ed-1790a627be97}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567717200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190828152820");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568367378");
user_pref("browser.slowStartup.averageTime", 1699);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1568367378);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567762528451");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"0ff6981a-56a9-405f-ae3e-c37ee274f624\",\"screenshots@mozilla.org\":\"c9966868-1aa0-4e2d-9bf8-fa0927ccaf32\",\"webcompat-reporter@mozilla.org\":\"5fc7d812-f0ba-4718-8496-cca147adac0a\",\"webcompat@mozilla.org\":\"f9f8a9a7-4455-4830-8628-f50f4146406d\",\"fxmonitor@mozilla.org\":\"c3f9ff68-6c61-4946-b033-373d9bedfcf7\",\"default-theme@mozilla.org\":\"cd302b90-5634-4996-9442-12e25b1f8adb\",\"google@search.mozilla.org\":\"29016e13-78c7-4ec2-b0a7-893b3647ffce\",\"amazondotcom@search.mozilla.org\":\"9084454e-3759-4a56-8938-79c90b3236bb\",\"bing@search.mozilla.org\":\"cd8039e2-2912-40c8-b75e-e94c6f4adbce\",\"ddg@search.mozilla.org\":\"d3acfb0f-c44c-46f1-932f-098b5c449500\",\"ebay@search.mozilla.org\":\"a1bb946c-784c-4202-a5ab-54fa6cc34a15\",\"twitter@search.mozilla.org\":\"2b47c8d7-3319-4dd4-96ce-3d406cfa3efe\",\"wikipedia@search.mozilla.org\":\"059460ec-8427-4ad9-a17d-4a94b6b95abc\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190327091052");
user_pref("media.gmp-manager.lastCheck", 1567762439);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "77add647-d36c-44ec-b535-6cd888c674c7");
user_pref("security.sandbox.plugin.tempDirSuffix", "06434865-e8da-4324-9beb-c0baffa70c12");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1568367376);
user_pref("toolkit.telemetry.cachedClientID", "28b4e995-ee3b-47a1-9f37-887e22d74f31");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
