// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567762449);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1568367426);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 45);
user_pref("browser.cache.disk.capacity", 716800);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567762419);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{95574a80-3f63-49ea-afae-2b13c582984f}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567717200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190828152820");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568367397");
user_pref("browser.slowStartup.averageTime", 1982);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1568367397);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1568367407002");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"23318220-1617-4154-97d8-4d4df41048ef\",\"screenshots@mozilla.org\":\"e373ca8c-bac2-443c-a26b-7ec183599f72\",\"webcompat-reporter@mozilla.org\":\"b80cf847-7565-4de7-9998-ec81e77cab88\",\"webcompat@mozilla.org\":\"0769bc83-9bab-4973-ab52-db603fdebcf5\",\"fxmonitor@mozilla.org\":\"2af707e9-918d-49e6-97d8-9436e2d672e0\",\"default-theme@mozilla.org\":\"f5777a99-0cff-4136-8700-9650adb4d0c3\",\"google@search.mozilla.org\":\"0661ccbf-e477-4f97-bd7b-cdba1bc844ab\",\"amazondotcom@search.mozilla.org\":\"40225655-62d7-4a1c-bfb8-cb7f301e4748\",\"bing@search.mozilla.org\":\"4132cee5-1f7b-4d5f-a69c-63ce7663385b\",\"ddg@search.mozilla.org\":\"f75a8b5c-be98-46d8-9cb5-62bf281a4c87\",\"ebay@search.mozilla.org\":\"457b256a-bdfe-4d6c-bfd2-1fd1a632790d\",\"twitter@search.mozilla.org\":\"40c09096-1bfa-43fa-acf8-9190f10e7bab\",\"wikipedia@search.mozilla.org\":\"08df95d5-a805-4547-ba9c-c01f2ac73a7d\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4bec63a7-de1d-43ab-9ed4-fa82a9baaa02");
user_pref("security.sandbox.plugin.tempDirSuffix", "fcd67041-1065-4d9b-b927-806161ed543f");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1568367395);
user_pref("toolkit.telemetry.cachedClientID", "3b1b73d3-9bac-448b-a4e6-ea96320d8ce2");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
