// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567762930);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567763050);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1568367425);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567762690);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567762570);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1567762810);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567763290);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567763170);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 273);
user_pref("browser.cache.disk.capacity", 716800);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567762420);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f8797399-f1df-414f-8b87-b4e94fde44ea}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567717200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568367396");
user_pref("browser.slowStartup.averageTime", 2003);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1568367395);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567762602343");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1567763110);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3f46debc-04e0-49c4-a905-061a7d7d0c9e\",\"screenshots@mozilla.org\":\"6e58f8c5-f895-4234-a5f3-0bce63f8a47f\",\"webcompat-reporter@mozilla.org\":\"2f8a4317-7af0-459d-88db-3ca80fbc77df\",\"webcompat@mozilla.org\":\"be5a8e59-7163-4ec8-825d-e074406f3eb3\",\"fxmonitor@mozilla.org\":\"59e68e74-f78a-4a80-888c-1472f8114753\",\"default-theme@mozilla.org\":\"2f9abd91-ce59-4152-81c6-6ed6de60faed\",\"google@search.mozilla.org\":\"8e9b55b5-6023-4737-a67a-b1724c1317d1\",\"amazondotcom@search.mozilla.org\":\"1324e79a-7033-458f-b841-6d7d46b74821\",\"bing@search.mozilla.org\":\"92fbb4e2-52f3-4ffe-bf3d-45f1e0494984\",\"ddg@search.mozilla.org\":\"0fa4318d-1368-4209-9a88-115839f4329e\",\"ebay@search.mozilla.org\":\"6b889a49-3903-4dc4-85c2-0fceb2ae93d4\",\"twitter@search.mozilla.org\":\"56028a26-6f6f-44dd-a839-39c912fd04ed\",\"wikipedia@search.mozilla.org\":\"c221ba3f-5197-4e09-9ef0-c9b1eac45a1e\"}");
user_pref("idle.lastDailyNotification", 1567762847);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190327091052");
user_pref("media.gmp-manager.lastCheck", 1567762470);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567762847);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6672d138-dfa7-471e-a6c4-f6980675cfe2");
user_pref("security.sandbox.plugin.tempDirSuffix", "59fd8b8f-f367-47e7-9c23-d3756085c715");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1567762847);
user_pref("toolkit.startup.last_success", 1568367393);
user_pref("toolkit.telemetry.cachedClientID", "2a634ce6-6693-4426-b0c8-4f594fd00efa");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
