// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567762659);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 829440);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567762629);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1b4f7b6b-702f-4726-87a6-2f8bbfbcb6b4}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567717200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191002193559");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1570785548");
user_pref("browser.slowStartup.averageTime", 3073);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20191002193559");
user_pref("browser.startup.homepage_override.mstone", "69.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1570785547);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0.2");
user_pref("extensions.lastPlatformVersion", "69.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"567918c4-c40d-47e5-b21c-33d72f237382\",\"screenshots@mozilla.org\":\"28aca23a-ef9f-433c-a47e-b17888f3f2b7\",\"webcompat-reporter@mozilla.org\":\"928664fc-0b43-454e-83b6-1ff356d5b8da\",\"webcompat@mozilla.org\":\"51317e67-f02b-4bf3-8ac0-cc71fbe1ba66\",\"fxmonitor@mozilla.org\":\"c3d22ff9-56a4-47c7-9c08-77537dd0bead\",\"default-theme@mozilla.org\":\"47d0a503-3cfd-4a1e-98b0-c4cb102d391f\",\"google@search.mozilla.org\":\"b93c4689-4d6c-42b4-8ef7-8237406b6bdd\",\"amazondotcom@search.mozilla.org\":\"50675a9a-54b1-4e79-b404-9bc456d0689b\",\"bing@search.mozilla.org\":\"5954f4f8-f82a-45d1-82ac-472351ad2f11\",\"ddg@search.mozilla.org\":\"a2ff78ab-acfd-42df-9925-4734a6987135\",\"ebay@search.mozilla.org\":\"8dea582f-e29e-42c7-a345-f183fb12de97\",\"twitter@search.mozilla.org\":\"2a6a4141-83e8-4d99-b8fe-8e8b9cadc7a2\",\"wikipedia@search.mozilla.org\":\"2d6cc6a1-59e6-4af7-a293-974c4b1cff2c\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3bf2cf60-35a9-4677-96b4-a6a2620abecc");
user_pref("security.sandbox.plugin.tempDirSuffix", "ef0d6003-dab5-4e8f-a7c2-bdcbdbcb43c8");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1570785543);
user_pref("toolkit.telemetry.cachedClientID", "eb8c6b81-cd24-47a7-b954-5a8bcf2f6818");
user_pref("toolkit.telemetry.previousBuildID", "20191002193559");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
